baseURL = "https://albertorg-web.onrender.com/"
languageCode = "es"
title = "albertorg Web"
theme = "paper"

[services]
  [services.disqus]
    shortname = "YOUR_DISQUS_SHORTNAME"     # use disqus comments

[params]
  # color style
  color = "dark"                            # Cambié de "linen" a "dark"
  customCSS = ["custom.css"]                # ← AÑADIDO: CSS personalizado
  
  # header social icons
  twitter = "albertoromaan"
  github = "albertoromaan"
  instagram = "albertoromaan_"
  linkedin = "albertoromaan"
  mastodon = "albertoromaan"
  threads = "albertoromaan"
  bluesky = "albertoromaan"
  rss = true
  
  # home page profile
  avatar = "GRAVATAR_EMAIL"
  name = "albertorg"
  bio = "Técnico Superior ASIR"
  
  # misc
  disableHLJS = true
  disablePostNavigation = true
  monoDarkIcon = true
  gravatarCdn = "GRAVATAR_CDN_LINK"
  math = true
  localKatex = false
  graphCommentId = "YOUR_GRAPH_COMMENT_ID"
  favicon = "favicon.ico"
  appleTouchIcon = "apple-touch-icon.png"
  direction = "ltr"
  
  # Secciones principales (importante para que aparezcan los posts)
  mainSections = ["posts"] 

[module]
  [[module.imports]]
    path = "github.com/nanxiaobei/hugo-paper"
